**00. PyTorch Fundamentals**

this is the first notebook

resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: go to "github discussion"

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## introduction

### creating a tensor

1. `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

2.

In [2]:
# scalar

scalar = torch.tensor(7)

scalar

tensor(7)

In [3]:
# how many dimension

scalar.ndim

0

In [4]:
# get tensor as python int

scalar.item()

7

In [5]:
# vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# vector.ndim -> returns Dimension of that tensor
vector.ndim

1

In [7]:
# vector.shape -> #numbers
vector.shape

torch.Size([2])

In [8]:
# Matrix

Matrix = torch.tensor([[7, 8],
                      [1, 2]])
Matrix

tensor([[7, 8],
        [1, 2]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix.shape

torch.Size([2, 2])

In [11]:
Matrix[0]

tensor([7, 8])

for each Tensor, try out these functions/operations:
name -> name of the tensor

i) name
ii) name.shape
iii) name.ndim
iv) name[idx]

In [12]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 4],
                        [3, 8, 9],
                        [9, 6, 3]]])


TENSOR2 = torch.tensor([[[1, 2, 4, 10],
                        [3, 8, 9, 1],
                        [9, 6, 3, 2]]])


In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 4],
        [3, 8, 9],
        [9, 6, 3]])

In [16]:
TENSOR2

tensor([[[ 1,  2,  4, 10],
         [ 3,  8,  9,  1],
         [ 9,  6,  3,  2]]])

In [17]:
TENSOR2.shape

torch.Size([1, 3, 4])

In [18]:
TENSOR2.ndim

3

In [19]:
TENSOR2[0]

tensor([[ 1,  2,  4, 10],
        [ 3,  8,  9,  1],
        [ 9,  6,  3,  2]])

**TENSOR2[1]** -> it's a block showing the

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-42-a1e006b9174c> in <cell line: 1>()
----> 1 TENSOR2[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1
```

## Random Tensor

Initially neural network starts with random tensors -> then, adjusts numbers by updating gradually

Start with random numbers -> look at data -> update random numbers => look at data -> update

In [20]:
# create random tensor

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9037, 0.8417, 0.3189, 0.7630],
        [0.0489, 0.2337, 0.7655, 0.4967],
        [0.8806, 0.3579, 0.9325, 0.5163]])

In [21]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [22]:
random_tensor = torch.rand(1, 10, 10);
random_tensor

tensor([[[0.3045, 0.4403, 0.4001, 0.5177, 0.7179, 0.0833, 0.4689, 0.5696,
          0.5220, 0.9585],
         [0.0772, 0.5714, 0.9686, 0.4299, 0.4574, 0.6747, 0.8074, 0.2831,
          0.7421, 0.4807],
         [0.6593, 0.9129, 0.6053, 0.7707, 0.5150, 0.7866, 0.9997, 0.4597,
          0.7283, 0.0075],
         [0.8213, 0.7880, 0.4750, 0.8780, 0.8217, 0.5631, 0.1299, 0.8408,
          0.5404, 0.0643],
         [0.4816, 0.1660, 0.5016, 0.3168, 0.2949, 0.1123, 0.4570, 0.5288,
          0.4864, 0.9548],
         [0.5556, 0.8059, 0.7447, 0.4804, 0.6736, 0.8934, 0.0630, 0.2130,
          0.5608, 0.7850],
         [0.4737, 0.5827, 0.6528, 0.5397, 0.3551, 0.5777, 0.2112, 0.5367,
          0.6112, 0.1631],
         [0.6024, 0.4488, 0.0361, 0.9144, 0.9947, 0.3591, 0.2159, 0.7304,
          0.2397, 0.6392],
         [0.7921, 0.9598, 0.8737, 0.2366, 0.1186, 0.2971, 0.7964, 0.9613,
          0.2433, 0.6078],
         [0.4865, 0.6089, 0.7750, 0.7053, 0.4309, 0.9921, 0.0288, 0.0795,
          0.2178,

In [23]:
random_tensor2 = torch.rand(10, 10, 10)
random_tensor2

tensor([[[0.5064, 0.1680, 0.2593, 0.1091, 0.6421, 0.3625, 0.7003, 0.7505,
          0.3793, 0.2341],
         [0.7518, 0.0538, 0.7392, 0.0200, 0.6615, 0.9685, 0.4472, 0.9464,
          0.9090, 0.9198],
         [0.0471, 0.2669, 0.2071, 0.4807, 0.2577, 0.1216, 0.2048, 0.1216,
          0.7037, 0.7266],
         [0.2535, 0.1950, 0.1549, 0.5070, 0.1168, 0.4425, 0.3045, 0.6791,
          0.1353, 0.8171],
         [0.2414, 0.5524, 0.8474, 0.6875, 0.8023, 0.6138, 0.0362, 0.6996,
          0.2998, 0.0739],
         [0.7239, 0.6694, 0.3792, 0.9279, 0.2868, 0.0647, 0.3314, 0.9258,
          0.6220, 0.7243],
         [0.1361, 0.8249, 0.6271, 0.5238, 0.1195, 0.8383, 0.2996, 0.1899,
          0.0251, 0.5685],
         [0.5194, 0.0079, 0.0732, 0.0176, 0.3050, 0.7917, 0.4795, 0.0641,
          0.5641, 0.7578],
         [0.7307, 0.8739, 0.1200, 0.0494, 0.9114, 0.0951, 0.9041, 0.8381,
          0.8237, 0.2046],
         [0.8427, 0.2123, 0.6443, 0.6562, 0.2697, 0.3073, 0.4915, 0.3625,
          0.7582,

In [24]:
# create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

## Tensor of Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
zeros.dtype

torch.float32

## Creating tensors in a range & tensors-lie

In [29]:
# use torch.range()
torch.range(0, 10)

<ipython-input-29-d8a01f916eaa>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).**

In [30]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# use torch.arange()
one_to_ten = torch.arange(start=1, end=10, step=3)
one_to_ten

tensor([1, 4, 7])

In [32]:
ranged_tensor = torch.arange(1, 100, 9)
ranged_tensor

tensor([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [33]:
# creating tensors like
ten_ranged_tensor = torch.arange(1, 10+1, 1)
zeros_like_ten_ranged_tensors = torch.zeros_like(input=ten_ranged_tensor)
ten_ranged_tensor, zeros_like_ten_ranged_tensors

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

## Tensors Datatypes

default date type = float32

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

**Official doc:** https://pytorch.org/docs/stable/tensors.html

**Precision on Computing:** https://en.wikipedia.org/wiki/Precision_(computer_science)

In [34]:
# float 32 tensor

float32_tensor = torch.tensor([3.0, 5.0, 4.0], dtype = None)
float32_tensor, float32_tensor.dtype

(tensor([3., 5., 4.]), torch.float32)

In [35]:
float16_tensor = torch.tensor([3.0, 5.0, 4.0], dtype = torch.float16)
float16_tensor

tensor([3., 5., 4.], dtype=torch.float16)

In [36]:
float16_tensor.dtype

torch.float16

In [37]:
float32_tensor2 = torch.tensor([3.0, 1.0, 8.0],
                               dtype=None, # what datatypes is the tensor (e.g. float32 or float16)
                               device=None, # which device is your tensor on (e.g. cpu, cuda)
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float32_tensor2, float32_tensor2.dtype

(tensor([3., 1., 8.]), torch.float32)

In [38]:
float16_tensor = float32_tensor2.type(torch.float16) #torch.float16 or torch.half
float16_tensor

tensor([3., 1., 8.], dtype=torch.float16)

In [39]:
float16_tensor * float32_tensor2

tensor([ 9.,  1., 64.])

In [40]:
int32_tensor = torch.tensor([3, 2, 1], dtype = torch.int32)
int32_tensor

tensor([3, 2, 1], dtype=torch.int32)

In [41]:
float32_tensor3 = torch.tensor([5, 4, 9], dtype=torch.float32)
float32_tensor3

tensor([5., 4., 9.])

In [42]:
int32_tensor * float32_tensor3

tensor([15.,  8.,  9.])

## Getting information from tensors (tensor attributes)

1. to get datatype from a tensor, we can use `tensor.dtype`
2. to get shape from a tensor, we can use `tensor.shape`
3. to get device from a tensor, we can use `tensor.device`

`a_tensor.shape` -> an attribute

`a_tensor.size()` -> a function

**but does the same work.**

**Creating a tensor(float64)**

In [43]:
# create a tensor(int)

a_tensor = torch.rand(3, 4)
# a_tensor = torch.rand(3, 4, device=torch.device("cuda"))
a_tensor

tensor([[0.5794, 0.2376, 0.7244, 0.6007],
        [0.9379, 0.1344, 0.7337, 0.2556],
        [0.2235, 0.0977, 0.2188, 0.7914]])

In [44]:
# find out details about that tensor
print(a_tensor)
print(f"Datetype of the tensor: {a_tensor.dtype}")
print(f"Shape of the tensor: {a_tensor.shape}")
print(f"Device of the tensor: {a_tensor.device}")

tensor([[0.5794, 0.2376, 0.7244, 0.6007],
        [0.9379, 0.1344, 0.7337, 0.2556],
        [0.2235, 0.0977, 0.2188, 0.7914]])
Datetype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


**Creating a int64 tensor**

In [46]:
# create a tensor(int64)
a_tensor_int = torch.randint(1, (2, 2))
a_tensor_int2 = torch.randint(low=0, high=100, size=(5,6), dtype=torch.int64, device=torch.device('cuda'))

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [47]:
# find out details about that tensor
print(a_tensor_int2)
print(f"Datatype of the tensor: {a_tensor_int2.dtype}")
print(f"Shape of the tensor: {a_tensor_int2.shape}")
print(f"Device, the tensor is on: {a_tensor_int2.device}")

NameError: name 'a_tensor_int2' is not defined

## Manipulating Tensors (tensor operations)
 Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. division
5. Matrix multiplication

In [ ]:
# addition, subtraction, mul & div

tensor = torch.tensor([1, 2, 4])

print(f"Tensor: {tensor}")
print(f"Addition: {tensor + 10}")
print(f"Substraction: {tensor - 10}")
print(f"Multiplication: {tensor * 10}")
print(f"Division: {tensor / 10}")

In [ ]:
# in-build functions of PyTorch

print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

***Matrix Multiplication:***

there are two types of multiplications in neural network and deep learning:

i) element-wise multiplication

ii) matrix multiplication (dot product)

***Matrix Multi.*** is by far the most used tensor operation inside neural network

In [ ]:
# element wise multiplication:

print(tensor)
print(tensor, " * ", tensor, " = ", tensor * tensor)

In [ ]:
# Matrix multiplication:

torch.matmul(tensor, tensor)

In [ ]:
# Matrix multiplication by hand;

1*1 + 2*2 + 4*4

**let's check the time difference between "using loop" vs "PyTorch function"**

In [48]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

NameError: name 'tensor' is not defined

In [49]:
%%time

torch.matmul(tensor, tensor)

NameError: name 'tensor' is not defined

The @ operator, introduced in Python 3.5 as the matrix multiplication operator (PEP 465), is essentially syntactic sugar for matrix multiplication. In PyTorch, it behaves similarly to torch.matmul for 2D tensors.

both torch.matmul and the @ operator are useful for matrix multiplication in PyTorch. For simple and straightforward 2D matrix multiplications, the @ operator is often more concise and readable. **For more complex operations, especially involving higher-dimensional tensors and broadcasting, torch.matmul is the better choice.**

Rules that need to be satisfied when performing matrix multiplication:

1. The **inner dimension** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimension**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

`torch.matmul(torch.rand(3, 2), torch.rand(3, 2))`

gives the following error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-91-9adeb7046560> in <cell line: 1>()
----> 1 torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.1980, 0.6128],
        [0.4959, 0.7672]])

In [51]:
torch.matmul(torch.rand(2, 4), torch.rand(4, 3)).shape

torch.Size([2, 3])

**One of the most common errors in deep learning:** shape error

In [52]:
# matrices for Matrix Multiplication:

tensor_x = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_y = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

`torch.mm()` is the short alias for `torch.matmul()`

`torch.mm(tensor_x, tensor_y)`

**Shows the following error**:

RuntimeError:                             Traceback (most recent call last)

----> 1 torch.mm(tensor_x, tensor_y)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

`tensor.T` -> gives Transpose of matrix "tensor"

In [53]:
# Transposing one of the two matrices so that inner dimension matches

print(tensor_y.T)

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [54]:
torch.mm(tensor_x, tensor_y.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [55]:
print(f"Before (Transpose): tensor_x = {tensor_x.shape}, tensor_y = {tensor_y.shape}")
print(f"After (Transpose): tensor_x = {tensor_x.shape}, tensor_y = {tensor_y.T.shape}")
print("\n")

print(f"Tensor_x = {tensor_x}")
print(f"Tensor_y.T = {tensor_y.T}")
print("\n")
print("Matrix Multiplication: ")
print(f"tensor_x @ tensor_y = ")
print(torch.mm(tensor_x, tensor_y.T))
print(f"Shape of tensor_x @ tensor_y.T = {torch.mm(tensor_x, tensor_y.T).shape}")

Before (Transpose): tensor_x = torch.Size([3, 2]), tensor_y = torch.Size([3, 2])
After (Transpose): tensor_x = torch.Size([3, 2]), tensor_y = torch.Size([2, 3])


Tensor_x = tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor_y.T = tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


Matrix Multiplication: 
tensor_x @ tensor_y = 
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Shape of tensor_x @ tensor_y.T = torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (Tensor aggregation)

**aggregation** because we'er going from large amount of numbers to small amount of numbers.

In [56]:
# create a tensor
x = torch.arange(1, 51, 5)
x

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [57]:
# finding the min

torch.min(x), x.min()  # either of these syntaxs work, they bascially do the same thing BTS

(tensor(1), tensor(1))

In [58]:
# finding the max

torch.max(x), x.max()

(tensor(46), tensor(46))

In [59]:
# finding the mean -> Note: the `torch.mean()` function requires a tensor of floating point or complex type to work

print(x.dtype)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

torch.int64


(tensor(23.5000), tensor(23.5000))

In [60]:
# finding the sum

torch.sum(x), x.sum()

(tensor(235), tensor(235))

**Positional min & max, known as Arg min & Arg max**

basically at which idx, min and max are *occurring*

In [61]:
# arg min (positional min)

torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [62]:
# arg max (positional max)

torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

Sometimes we don't the actual min/max value, but just want to know where they appear. This is helpful, when we use the **softmax activation** later on.

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - combine multiple tensors on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stack)

* Squeeze - removes all `1` dimensions from a tenor

* Unsqueeze - adds a `1` dimension to a target tensor

* Permute - Return a view of the input with dimensions permuted (swapped) in a certail way

In [64]:
# let's create a tensor

tensor_a = torch.arange(1.0, 10.0)
tensor_a, tensor_a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# add an extra dimension
# reshape() needs to be compatible with the original dimension
# tensor_a_reshaped = tensor_a.reshape(1, 7) -> gives error
# tensor_a_reshaped = tensor_a.reshape(7, 1) -> gives error
tensor_a_reshaped = tensor_a.reshape(1, 9) # works
print(tensor_a_reshaped, " ", tensor_a_reshaped.shape)
tensor_a_reshaped = tensor_a.reshape(9, 1)
print(tensor_a_reshaped, " ", tensor_a_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])   torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])   torch.Size([9, 1])


In [70]:
tensor_b = torch.arange(1.0, 13.0)
print("Original tensor_b = ", tensor_b, " ", tensor_b.shape)
tensor_b_reshaped = tensor_b.reshape(3, 4)
print("After reshaping: ", tensor_b_reshaped, " ", tensor_b.shape)

Original tensor_b =  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])   torch.Size([12])
After reshaping:  tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])   torch.Size([12])


In [74]:
# change the view

abc = tensor_b.view(1, 12)   #name.view(a, b) where a & b both are included
abc, abc.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [77]:
# but both abc & tensor_b shares the same memory so,
# changing abc will also change tensor_b, and vice verse

# abc[0, 0] = 99 -> does the same thing, but diff syntax
abc[0][0] = 99
abc, tensor_b

(tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [84]:
# stack tensors on top of each other
ab = torch.arange(1.0, 11.0)
ab_stacked = torch.stack([ab, ab, ab]) # default dim = 0
print(ab_stacked)
ab_stacked = torch.stack([ab, ab, ab], dim = 1)
print(ab_stacked)
# ab_stacked = torch.stack([ab, ab, ab], dim = 2)
# print(ab_stacked)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])


In [89]:
#hstack
print("hstack_ab: ", torch.hstack([ab, ab, ab]))

#vstack
print("vstack_ab: ", torch.vstack([ab, ab, ab]))

hstack_ab:  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.])
vstack_ab:  tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


In [101]:
# name.squeeze() -> removes all the 1 dimension from a tensor
e = torch.rand(1, 2, 1, 4)
print(f"prev tensor e = {e}, shape = {e.shape}")

e_squeezed = e.squeeze()
print(f"after sqz,  tensor e = {e_squeezed}, shape = {e_squeezed.shape}")

prev tensor e = tensor([[[[0.1026, 0.4404, 0.3107, 0.9583]],

         [[0.5893, 0.4462, 0.3546, 0.6375]]]]), shape = torch.Size([1, 2, 1, 4])
after sqz,  tensor e = tensor([[0.1026, 0.4404, 0.3107, 0.9583],
        [0.5893, 0.4462, 0.3546, 0.6375]]), shape = torch.Size([2, 4])


In [105]:
# name.unsqueeze() -> adds a single dimension at a target tensor at a specific dimension

print("e_squeezed: ", e_squeezed, " , shape: ", e_squeezed.shape)
e_unsqzed = e_squeezed.unsqueeze(dim=0) # default dim = 0
print("e_unsqueezed(at dim = 0): ", e_unsqzed, " , shape: ", e_unsqzed.shape)

e_unsqzed1 = e_squeezed.unsqueeze(dim=1) # default dim = 0
print("e_unsqueezed(at dim = 1): ", e_unsqzed1, " , shape: ", e_unsqzed1.shape)

e_unsqzed2 = e_squeezed.unsqueeze(dim=2) # default dim = 0
print("e_unsqueezed(at dim = 2): ", e_unsqzed2, " , shape: ", e_unsqzed2.shape)

e_squeezed:  tensor([[0.1026, 0.4404, 0.3107, 0.9583],
        [0.5893, 0.4462, 0.3546, 0.6375]])  , shape:  torch.Size([2, 4])
e_unsqueezed(at dim = 0):  tensor([[[0.1026, 0.4404, 0.3107, 0.9583],
         [0.5893, 0.4462, 0.3546, 0.6375]]])  , shape:  torch.Size([1, 2, 4])
e_unsqueezed(at dim = 1):  tensor([[[0.1026, 0.4404, 0.3107, 0.9583]],

        [[0.5893, 0.4462, 0.3546, 0.6375]]])  , shape:  torch.Size([2, 1, 4])
e_unsqueezed(at dim = 2):  tensor([[[0.1026],
         [0.4404],
         [0.3107],
         [0.9583]],

        [[0.5893],
         [0.4462],
         [0.3546],
         [0.6375]]])  , shape:  torch.Size([2, 4, 1])


torch.permute -> returns **a view** of the original tensor with its dimensions permuted

In [117]:
# name.permute() -> rearrange the dimensions of a tensor at a specific order
# normally permute is seen to be used with images
t_original = torch.rand(size=(224, 224, 3)) #[height, weight, color_channels]
print("Shape of original tensor: ", t_original.shape)

# let's change the original tensor's dim/axis with [color_channels, height, weight] using permute
t_permuted = t_original.permute(2, 0, 1) # [color_channels, height, weight]
print("Shape after permuting: ", t_permuted.shape)
print("\n")

print("NOTE: as torch.permute return a view of the original tensor, \nt_permuted & t_original will share the same memory")
print(f"")
print(t_original[0, 0, 0])
print(t_permuted[0, 0, 0])
t_original[0, 0, 0] = -11
print(t_permuted[0, 0, 0])

Shape of original tensor:  torch.Size([224, 224, 3])
Shape after permuting:  torch.Size([3, 224, 224])


NOTE: as torch.permute return a view of the original tensor, 
t_permuted & t_original will share the same memory

tensor(0.0968)
tensor(0.0968)
tensor(-11.)


## Indexing (selecting data form tensors)

Indexing with PyTorch is similiar to indexing with NumPy

In [118]:
import torch

f = torch.arange(1, 17).reshape(1, 4, 4)
f, f.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]]),
 torch.Size([1, 4, 4]))

In [123]:
print(f)
print(f[0])
print(f[0][0])
print(f[0][0][0])
print(f[0][0][1])
print(f[:, 0, 0])
print(f[:, :, 0])
print(f[:, 1, 0])
print(f[:, :, 1])
print(f[:, :, 2])
print(f[:, :, :])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor([1, 2, 3, 4])
tensor(1)
tensor(2)
tensor([1])
tensor([[ 1,  5,  9, 13]])
tensor([5])
tensor([[ 2,  6, 10, 14]])
tensor([[ 3,  7, 11, 15]])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])


In [124]:
print(f[0, 3, 3])

tensor(16)


In [125]:
print(f[0, :, 3])

tensor([ 4,  8, 12, 16])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

and because of this, PyTorch has functionality to interact with it.

* Data in NumPy array, want in PyTorch tensor -> `torch.numpy(ndarray)`
* PyTorch tensor, want in NumPy array -> `torch.tensor.numpy()`

In [9]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 11.0)
print("NumPy array default dtype: ", array.dtype)

tensor = torch.from_numpy(array)
print("Tensor2: ", tensor)  # as narray's default dtype is 'flaot64', tensor becomes of 'flaot64'

tensor2 = torch.from_numpy(array).type(torch.float32) # chanding dtype from float64 to float32
print("Tensor2 = ", tensor2, " ", tensor2.dtype)

NumPy array default dtype:  float64
Tensor2:  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
Tensor2 =  tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])   torch.float32


In [14]:
# Tensor to NumPy array

tensor_p = torch.ones(10)
array2 = tensor_p.numpy()
print("dtype of tensor: ", tensor_p.dtype)   # default dtype for tensor -> float32
print("dtype of narray: ", array2.dtype)

dtype of tensor:  torch.float32
dtype of narray:  float32


## Reproducibility (trying to take random out of random)

in short how neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representators of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch, there comes the concept of a **random seed**.

In [16]:
## let's make some random but reproducible tensors

import torch

# setting the random seed
RANDOM_SEED = 42 # this number can be any numberic value, it represents different flavours of randomness

torch.manual_seed(RANDOM_SEED) # setting up the manual seed for reproducive random numbers

random_tensor_A = torch.rand(3, 5)
random_tensor_B = torch.rand(3, 5)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

# it's not reproducing the same random numbers because after setting the manual_seed, only one
# function after that works for that manual seed. So creating the second random numbers, we
# need to set the manual seed again.

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [21]:
import torch

# setting the random seed
RANDOM_SEED = 42 # this number can be anything

torch.manual_seed(RANDOM_SEED) # setting up the manual seed for reproducive random numbers
random_tensor_A = torch.rand(3, 5)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 5)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


**Resources regarding Reproducibility & random seed:**

* https://pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

Getting a GPU:

* Easiest - Use Google Colab for a free GPU
* Use your own GPU
* Use cloud computing - GCP, AWS, Azure etc. These services allow you to rent computers on the cloud and access them.


For PyTorch, since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.

E.g. run on GPU if it's available, else on CPU(default)


**Device Agnostic code (PyTorch doc):**

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [34]:
# check for GPU access

# approch 1: nvidia command
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [35]:
#approach 2: using PyTorch
import torch

torch.cuda.is_available()

False

In [36]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [37]:
# Count number of devices
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [40]:
#create a tensor (default on the CPU)

tensor_x = torch.tensor([1, 2, 4])
tensor_x, tensor_x.device

(tensor([1, 2, 4]), device(type='cpu'))

In [44]:
# move tensor_x to GPU(if available)

device2 = "cuda" if torch.cuda.is_available() else "cpu"
tensor_x_gpu = tensor_x.to(device2)   #name.to(device_name) -> is used to move models & tensors to other devices
tensor_x_gpu, tensor_x_gpu.device   # still on CPU, because of no GPU

(tensor([1, 2, 4]), device(type='cpu'))

## Moving tensors back to CPU

e.g. NumPy only works on CPU

In [47]:
# moving tensor back to CPU as NumPy does only work on CPU

tensor_x_cpu = tensor_x_gpu.to("cpu")
tensor_x_cpu.device

device(type='cpu')

In [49]:
# To fix the GPU tensor with NumPy issue, we first need to set it back to the CPU

tensor_back_on_cpu = tensor_x_gpu.cpu().numpy()  # name.cpu() -> also works to change back to CPU
tensor_back_on_cpu

array([1, 2, 4])

---------------------------> END Of **First Module**(PyTorch Fundamentals) <---------------------------

**Exercises & Extra-Curriculum:**

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises